# Basic set up for package managers.

version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"
    timezone: "Europe/Stockholm"

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
    time: "00:00"
    timezone: "Europe/Stockholm"
