# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=2000"]

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language: python
        types_or: [python, pyi]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config=Discord_bot/tox.ini]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.3
    hooks:
      - id: pylint
        language: system
        args:
          - --output-format=colorized
          - --errors-only
          - --rcfile=Discord_bot/pyproject.toml

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort


  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest -v
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
