name: Create release

on:
  workflow_run:
    workflows: ["tag bump"]
    types:
      - completed
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Print GitHub reference
      run: echo "GitHub reference: ${{ github.ref }}"
      
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')

