name: Create release

on:
  workflow_run:
    workflows: ["tag bump"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        uses: actions/github-script@v4
        id: latest_tag
        with:
          script: |
            const { data } = await github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.log(data[0].name);
            return data[0].name;
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest_tag.outputs.result }}
          body_path: ${{ github.workspace }}-CHANGELOG.md
          token: ${{ secrets.WORKFLOW }}
        env:
          GITHUB_REPOSITORY: mindriddler/chatgpt-discord-bot



