name: Create release

on:
  workflow_run:
    workflows: ["tag bump"]
    types:
      - completed
      
permissions:
  contents: write
  discussions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        uses: dawidd6/action-get-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.WORKFLOW }}
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: mindriddler/chatgpt-discord-bot






