name: Create release

on:
  workflow_run:
    workflows: ["tag bump"]
    types:
      - completed
      
permissions:
  contents: write
  discussions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        uses: actions/github-script@v4
        id: latest_tag
        with:
          script: |
            const { data } = await github.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const tagName = data[0].name.replace(/"/g, '');
            console.log(tagName);
            return tagName;
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest_tag.outputs.result }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.WORKFLOW }}
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: mindriddler/chatgpt-discord-bot




