name: Create release

on:
 push:
   branches:
     - main

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest_tag.outputs.result }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.WORKFLOW }}
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: mindriddler/chatgpt-discord-bot
