name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build \
          --file Docker/Dockerfile \
          --tag chatgpt-discord-bot:$(date +%s) \
          --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}


