name: Docker Image CI Dev

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #v2.1.0
        with:
          registry: ghcr.io
          username: mindriddler
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert branch name
        id: convert_branch_name
        run: echo "branch_name=$(sed 's|/|_|g' <<<${{ github.head_ref }} )" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          build-args: GITHUB_ACTION=true
          file: ./Docker/Dockerfile
          push: true
          tags: |
            ghcr.io/mindriddler/chatgpt-discord-bot-dev:${{ github.actor }}
            ghcr.io/mindriddler/chatgpt-discord-bot-dev:${{ github.event.number }}
            ghcr.io/mindriddler/chatgpt-discord-bot-dev:${{ steps.convert_branch_name.outputs.branch_name }}
          provenance: false




