name: Docker Image CI Dev

on:
  push:
    branches: 
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build --file Docker/Dockerfile --tag ghcr.io/mindriddler/chatgpt-discord-bot-dev:latest .
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/mindriddler/chatgpt-discord-bot-dev:latest




